name=input("Name : ")
age=int(input("Age : "))
print("Enter marks for the following")
sub1=int(input("Subject 1 : "))
sub2=int(input("Subject 2 : "))
sub3=int(input("Subject 3 : "))
sub4=int(input("Subject 4 : "))
sub5=int(input("Subject 5 : "))
tot=sub1+sub2+sub3+sub4+sub5
avg=tot/5
print("")
print("-----------------")
print("Name \t:",name)
print("Age \t:",age)
print("-----------------")
print("Subject 1 :",sub1)
print("Subject 2 :",sub2)
print("Subject 3 :",sub3)
print("Subject 4 :",sub4)
print("Subject 5 :",sub5)
print("-----------------")
print("Total \t:",tot)
print("Average :",avg)
print("-----------------")